name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run go test
    runs-on: ubuntu-latest
    env:
      # TestPatcher:
      #   absolute path in localsession.json
      # TestCases:
      #   hardcoded obselete json
      # Test_goParser_ParseNode:
      #   test tries to retrieve non-existent node
      # TestParser_NodeFieldsConsistency:
      #   Vars.Content only includes name, not whole body
      SKIPPED_TESTS: >-
        TestPatcher|TestCases|Test_goParser_ParseNode|TestParser_NodeFieldsConsistency

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rust-analyzer

      - name: Install gopls
        run: go install golang.org/x/tools/gopls@latest

      - name: Run all tests
        run: go test ./lang/... -skip '${{ env.SKIPPED_TESTS }}'
