name: Simple Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: prepare rls
      run: rustup component add rust-analyzer
    - name: check linenos
      run: ./script/check_all_linenos.sh

